### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Lokilittle** [Tritschla/Resilio4SteamDeck#1]
Hello, thank you for making this, unfortunately I get this in my terminal and nothing installs.

==> Appending keys from archlinux.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2023-04-21
:: Synchronizing package databases...
 jupiter-rel                                                                                      87.4 KiB   243 KiB/s 00:00 [###########################################################################] 100%
 holo-rel                                                                                         41.9 KiB   117 KiB/s 00:00 [###########################################################################] 100%
 core-rel                                                                                        157.3 KiB   414 KiB/s 00:00 [###########################################################################] 100%
 extra-rel                                                                                      1721.5 KiB  3.82 MiB/s 00:00 [###########################################################################] 100%
 community-rel                                                                                     7.1 MiB  10.2 MiB/s 00:01 [###########################################################################] 100%
 multilib-rel                                                                                    168.7 KiB   405 KiB/s 00:00 [###########################################################################] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) lib32-libxcrypt-compat-4.4.28-2

Total Download Size:   0.07 MiB
Total Installed Size:  0.18 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 lib32-libxcrypt-compat-4.4.28-2-x86_64                                                           70.7 KiB   384 KiB/s 00:00 [###########################################################################] 100%
(1/1) checking keys in keyring                                                                                               [###########################################################################] 100%
(1/1) checking package integrity                                                                                             [###########################################################################] 100%
error: lib32-libxcrypt-compat: signature from "Alexander Epaneshnikov <email@alex19ep.me>" is unknown trust
:: File /var/cache/pacman/pkg/lib32-libxcrypt-compat-4.4.28-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.

**Comment by Tritschla** [comment]
Hi,

I've updated the script to use a different command in regards to setup the needed keyring.
I hope this resolves the issue.

Please launch the "InstallResilio4SteamDeck.desktop" (downloaded in step 1) again to see, if the installation is now working.

**Comment by Lokilittle** [comment]
I downloaded the new script and still no install. I tried running the install.sh line by line in terminal and I get error here.
47: sudo -S pacman -Syyu --noconfirm lib32-libxcrypt-compat

The error message is:

error: lib32-libxcrypt-compat: signature from "Alexander Epaneshnikov <email@alex19ep.me>" is unknown trust
:: File /var/cache/pacman/pkg/lib32-libxcrypt-compat-4.4.28-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.

**Comment by Tritschla** [comment]
And I renewed the script to use "echo "$PASSWORD" | sudo pacman -Syy --noconfirm" before trying to install the package. Please may you test this?

**Comment by Lokilittle** [comment]
I get the same error with the updated package. I'm sorry, I'm new to linux.

**Comment by Tritschla** [comment]
The script is asking you to delete the corrupted file, did you do that?
If not, please do that and rerun the whole script

**Comment by Lokilittle** [comment]
I've tried to delete the file but I can't find it either in terminal or through the dolphin file browser.

**Comment by Tritschla** [comment]
when you use the command "sudo -S pacman -Syyu --noconfirm lib32-libxcrypt-compat" it is giving you the error message following with "Do you want to delete it? [Y/n]". Please press Y and hit enter to delete the file

**Comment by Tritschla** [comment]
My bad :-)
sudo -S pacman -Syyu lib32-libxcrypt-compat makes it, so you can go on.

**Comment by Tritschla** [comment]
ok, thank you for the feedback. I hope that the tool now will run fine for you. I will try to get the situation rebuilt on my side to have a deeper look how the script could get this problem solved for you automatically if you want to use it in the fututre

**Comment by Tritschla** [comment]
Did you had the opportiunity to test this or should we leave this for now, since it is working for you, the way you got it working?

**Comment by Tritschla** [comment]
Please note, this issue is set to solve, since it is based on the same problem as the more frequent issue #2
